### ISSUE TITLE
TsDocs for API documentation.

### ISSUE THREAD

**Issue by Istar-Eldritch** [repositive/event-store#30]
Use https://github.com/Microsoft/tsdoc for documentation of API and host it in gh-pages.

Expected outcomes:
* [ ] High level concepts
* [ ] Documentation of the event store public API, with explanations of any internal behaviour that should be considered during usage. Things like events not being saved prior to a listener being called, etc.### 
* [ ] Automatic doc generation based on the latest build from the master branch on CI.

**Comment by jamwaffles** [comment]
Personally I'd like to see:

* [ ] High level concepts
* [ ] Documentation of the event store public API, with explanations of any internal behaviour that should be considered during usage. Things like events not being saved prior to a listener being called, etc.###

**Comment by aredshaw** [comment]
I might be able to help, but I would probably write it in markdown, if that is OK.
Are these REST APIs?
I would need to know the base path and endpoints.
Also, a list of possible methods and parameters.
And of course an API Key if one is required.

**Comment by jamwaffles** [comment]
Hi, thanks for offering to help out! event-store is a Typescript module (eventually to be distributed on NPM) that offers an implementation of the [event-sourcing pattern](https://microservices.io/patterns/data/event-sourcing.html), namely the ability to store, emit, receive and aggregate events. It lacks good documentation and examples, hence this issue.

The main export of this package is [the `EventStore` class](https://github.com/repositive/event-store/blob/master/src/event-store.ts#L36). You may want to start there and work forward to get to grips with how this package works. We could really use some minimal examples to ease this process, so if you're interested in using event-store, an example or two from the perspective of a first-time user would be greatly appreciated. There's no HTTP API for this package as it is designed to be integrated into other software.

> but I would probably write it in markdown, if that is OK

We're looking to be able to generate documentation from code comments _a la_ Rustdoc using TSDoc, so as long as the markdown lives inside code comments and has fields that conform to TSDoc standards, that's absolutely fine. Thanks for showing an interest!

**Comment by aredshaw** [comment]
I was hoping to work on something with HTTP API needs. Thanks for replying though.
